-- ============================================================
-- Este fichero ya no hace nada. Se deja porque lo de dentro
-- explica un fallo que costó dos intentos.
--
-- Los extras salían repetidos: `db/tarifas.sql` los insertaba
-- con `on conflict do nothing` A SECAS, sin decir sobre qué
-- columna, y sin columna eso no detecta nada. Cada vez que se
-- aplicaba el fichero, los siete extras entraban otra vez.
--
-- El arreglo fue `on conflict (nombre) do nothing` más una
-- restricción de unicidad en `extra.nombre`. La restricción se
-- puso primero AQUÍ, y este fichero se aplicaba el último: el
-- `on conflict (nombre)` de tarifas.sql se encontraba con que
-- esa restricción todavía no existía y abortaba la instalación
-- entera con
--
--   42P10: there is no unique or exclusion constraint matching
--          the ON CONFLICT specification
--
-- La lección: una restricción tiene que crearse ANTES de que
-- alguien la nombre, y eso significa en el mismo fichero, entre
-- la tabla y el insert. Está en db/tarifas.sql, justo después
-- del `create table extra`.
-- ============================================================
